### ISSUE TITLE
assign is not a function

### ISSUE THREAD

**Issue by F-loat** [okoala/egg-jwt#11]
使用了egg-jwt的接口都会出错，http错误码500，错误信息为assign is not a function，引用方式应该没错的，麻烦帮忙看下是什么原因报错

``` javascript
// plugin.js
exports.jwt = {
  enable: true,
  package: 'egg-jwt',
};

// config.default.js
config.jwt = {
  secret: '123456',
  enable: true,
  ignore: '/api/login',
};
```

```
HEADERS

host 127.0.0.1:7001
pragma no-cache
cache-control no-cache
authorization Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1OTZhZmQwZGM3NjhmYjMzODhmMzk2YTIiLCJpYXQiOjE1MDAxODY5NzN9.wnlIngJSVekgYSGHoCzji-GV6kiWAlwZ2hwd0LAU86s
user-agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 appservice webview/100000
content-type application/json
accept */*
referer https://servicewechat.com/wx4228108b5fb42de1/devtools/page-frame.html
accept-encoding gzip, deflate, sdch
accept-language zh-CN,zh;q=0.8
```

```
2017-07-16 14:59:17,023 ERROR 7256 [-/127.0.0.1/-/5ms GET /api/user] nodejs.TypeError: assign is not a function
    at Object.get locals [as locals] (C:\Users\F-loat\Desktop\ourauto\server\node_modules\egg\app\extend\context.js:154:22)
    at Object.get state [as state] (C:\Users\F-loat\Desktop\ourauto\server\node_modules\egg\app\extend\context.js:176:16)
    at jwt (C:\Users\F-loat\Desktop\ourauto\server\node_modules\koa-jwt\lib\index.js:29:23)
    at Object.callFn (C:\Users\F-loat\Desktop\ourauto\server\node_modules\egg-core\lib\utils\index.js:45:15)
    at callFn.next (<anonymous>)
    at onFulfilled (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:65:19)
    at C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:54:5
    at Promise (<anonymous>)
    at Object.co (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:50:10)
    at Object.toPromise (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:118:63)
    at next (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:99:29)
    at onFulfilled (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:69:7)
    at C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:54:5
    at Promise (<anonymous>)
    at Object.co (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:50:10)
    at Object.toPromise (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:118:63)
    at next (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:99:29)
    at onFulfilled (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:69:7)
    at C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:54:5
    at Promise (<anonymous>)
    at Object.co (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:50:10)
    at Object.createPromise (C:\Users\F-loat\Desktop\ourauto\server\node_modules\co\index.js:30:15)
    at Server.handleRequest (C:\Users\F-loat\Desktop\ourauto\server\node_modules\koa\lib\application.js:136:8)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
```

**Comment by F-loat** [comment]
新建项目后，就没这个问题了，
