### ISSUE TITLE
请问verify时，怎么处理错误

### ISSUE THREAD

**Issue by wuyunjiang** [okoala/egg-jwt#20]
使用`(token, secret,callbback)`callback只能接收到一个参数，无法处理错误
控制台直接打印错误
```
{ JsonWebTokenError: 错误信息
    at AsyncFunction.module.exports [as verify] (/data/webSite/wxtest.wuyunjiang.cn-server/node_modules/jsonwebtoken/verify.js:49:17)
    at jwtAuth (/data/webSite/wxtest.wuyunjiang.cn-server/app/middleware/jwtAuth.js:6:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'JsonWebTokenError', message: '错误信息' }
```

**Comment by li305263** [comment]
怎么全局verify token ?
